#!/usr/bin/env bash

## Initialize a Docksal powered Wordpress site
##
## Usage: fin init

# Abort if anything fails
set -e

#-------------------------- Settings --------------------------------

# PROJECT_ROOT is passed from fin.
# The following variables are configured in the '.env' file: DOCROOT, VIRTUAL_HOST.

DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"

#-------------------------- END: Settings --------------------------------

#-------------------------- Helper functions --------------------------------

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[42m'
yellow='\033[1;33m'
NC='\033[0m'

echo-red () { echo -e "${red}$1${NC}"; }
echo-green () { echo -e "${green}$1${NC}"; }
echo-green-bg () { echo -e "${green_bg}$1${NC}"; }
echo-yellow () { echo -e "${yellow}$1${NC}"; }

is_windows ()
{
	local res=$(uname | grep 'CYGWIN_NT')
	if [[ "$res" != "" ]]; then
		return 0
	else
		return 1
	fi
}

#-------------------------- END: Helper functions --------------------------------

#-------------------------- Functions --------------------------------

# Generate wp-config.php file
generate_config ()
{
	cd $DOCROOT_PATH

	extra=$(cat <<PHP
define('WP_DEBUG', true);
define('AS3CF_AWS_ACCESS_KEY_ID', 'AKIAJKV3K2DUW26C4U3A');
define('AS3CF_AWS_SECRET_ACCESS_KEY', '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');
PHP
)

	fin exec "rm -f wp-config.php"
	fin exec "wp core config --dbname=${MYSQL_DATABASE} \
	--dbuser=${MYSQL_USER} \
	--dbpass=${MYSQL_PASSWORD} \
	--dbhost=db \
	--extra-php=\"$extra\""
}

# Install site
site_install ()
{
	cd $DOCROOT_PATH

	fin exec "wp core install \
		--url=${VIRTUAL_HOST} \
		--title='AutoSound' \
		--admin_user=${WP_ADMIN_USER} \
		--admin_password=${WP_ADMIN_PASS} \
		--admin_email=${WP_ADMIN_EMAIL}"
}

activate_plugins ()
{
	cd $DOCROOT_PATH

	fin exec "wp plugin activate --all"
}

activate_theme ()
{
	cd $DOCROOT_PATH

	fin exec "wp theme activate autosound"
}

pull_db ()
{
	cd $DOCROOT_PATH

	fin exec "wp migratedb pull http://tagprints.com/wordpress W10PpkkYIUHlk8ARlfG/ZSvEhh+u41kbGvRtGprR --find=//tagprints.com,/var/www/html --replace=//${VIRTUAL_HOST},${DOCROOT_PATH}"
}

deactivate_plugins ()
{
	cd $DOCROOT_PATH

	fin exec "wp plugin deactivate w3-total-cache gravity-forms-no-captcha-recaptcha"
}

#-------------------------- END: Functions --------------------------------

#-------------------------- Execution --------------------------------

if [[ "$PROJECT_ROOT" == "" ]]; then
	echo-red "\$PROJECT_ROOT is not set"
	exit 1
fi

if [[ $DOCKER_RUNNING == "true" ]]; then
	echo -e "${green_bg} Step 1 ${NC}${green} Recreating services...${NC}"
	fin reset -f
else
	echo -e "${green_bg} Step 1 ${NC}${green} Creating services...${NC}"
	fin up
fi

echo "Waiting 10s for MySQL to initialize...";
sleep 10

# Project initialization steps
echo -e "${green_bg} Step 2 ${NC}${green} Generating wp-config.php...${NC}"
generate_config

echo -e "${green_bg} Step 3 ${NC}${green} Installing site...${NC}"
time site_install

echo -e "${green_bg} Step 4 ${NC}${green} Activating plugins...${NC}"
time activate_plugins

echo -e "${green_bg} Step 5 ${NC}${green} Activating theme...${NC}"
time activate_theme

# echo -e "${green_bg} Step 6 ${NC}${green} Pulling database...${NC}"
# time pull_db

# echo -e "${green_bg} Step 7 ${NC}${green} Deactivating plugins for dev...${NC}"
# time deactivate_plugins

if is_windows; then
	echo-green "Add ${VIRTUAL_HOST} to your hosts file (/etc/hosts), e.g.:"
	echo-green "192.168.64.100  ${VIRTUAL_HOST}"
	echo
fi

echo -en "${green_bg} DONE! ${NC} "
echo -e "Open ${yellow}http://${VIRTUAL_HOST}${NC} in your browser to verify the setup."
echo -e "Admin panel: ${yellow}http://${VIRTUAL_HOST}/wp-admin${NC}. User/password: ${yellow}${WP_ADMIN_USER}/${WP_ADMIN_PASS}${NC}  "

#-------------------------- END: Execution --------------------------------
